name: "Setup Conda Environment"
description: "Restore cache and install conda environment"

runs:
  using: composite
  steps:
    - name: Restore conda package cache
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('valska_env.yaml') }}

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: valska
        environment-file: valska_env.yaml
        # We do not need the base environment to be activated as well
        auto-activate: true
        use-mamba: true
        conda-solver: libmamba
        pkgs-dirs: ~/conda_pkgs_dir
        channel-priority: strict