# Pre-commit hooks configuration for ValSKA-HERA-beam-FWHM
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: ^docs/

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        exclude: \.ipynb$

      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        exclude: \.ipynb$

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]

      - id: nbqa-isort
        name: nbqa-isort
        entry: nbqa isort
        language: system
        files: \.ipynb$

      - id: nbqa-black
        name: nbqa-black
        entry: nbqa black
        language: system
        files: \.ipynb$

      - id: nbqa-flake8
        name: nbqa-flake8
        entry: nbqa flake8
        language: system
        files: \.ipynb$

      - id: nbqa-pylint
        name: nbqa-pylint
        entry: nbqa pylint
        language: system
        files: \.ipynb$
