on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    # conda-incubator requires the bash shell in login mode
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v5
    - name: echo
      run: |
        echo "hello"
