name: ValSKA CI/CD Pipeline

on: 
  pull_request

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install dependencies
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache if valska_env.yaml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('valska_env.yaml') }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: valska
        #channel-priority: strict
        environment-file: valska_env.yaml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
        # We do not need the base environment to be activated as well
        auto-activate: true
    - name: Pre-commit
      run: pre-commit run --all-files
    - name: Upload Lint Results
      if: always() # Ensures reports upload even if linting fails
      uses: actions/upload-artifact@v4
      with:
        name: lint-reports
        path: build/reports/*.xml  

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v5
    - name: Install dependencies
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache if valska_env.yaml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('valska_env.yaml') }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: valska
        #channel-priority: strict
        environment-file: valska_env.yaml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
        # We do not need the base environment to be activated as well
        auto-activate: true
    - name: Test with pytest
      run: |
        make python-test
    - name: Test notebooks
      run: |
        make notebook-test

  docs:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v5
    - name: Install dependencies
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache if valska_env.yaml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('valska_env.yaml') }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: valska
        #channel-priority: strict
        environment-file: valska_env.yaml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
        # We do not need the base environment to be activated as well
        auto-activate: true
    - name: Build docs
      run: |
        sphinx-build -W -b html docs/source/ docs/_build/html